name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # or master if your default branch is master
  pull_request:
    branches:
      - main  # or master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # You can use a different version if necessary

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: 'Upload artifact'
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: ./dist  # or the folder where Vite builds the project

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Static Web Apps Deploy
      uses: azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_API_TOKEN }}
        action: 'upload'
        app_location: '/'  # Path to the app (typically root if it's a Vite app)
        api_location: ''  # Leave blank if no API (serverless functions)
        output_location: './dist'  # Where the built app is located (dist is the default for Vite)
